"""
AI Service Layer.

Encapsulates all interactions with the Google Gemini API using the official Google GenAI SDK.
Enforces structured JSON generation, token conservation, strict schema validation,
and seamless fallback recovery for offline/missing API key scenarios.
"""

import json
import logging
from typing import List, Optional, Dict, Any
from fastapi import HTTPException, status
from pydantic import BaseModel, Field

from app.config import settings

logger = logging.getLogger("ai_service")


# Pydantic Schemas for AI Structured Output Validation
class AIRoadmapTopic(BaseModel):
    """Schema for individual topic generated by AI."""
    title: str = Field(..., description="Concise, clear topic title")
    description: str = Field(..., description="Summary of skills and concepts covered")
    sequence_order: int = Field(..., description="Prerequisite order (1, 2, 3...)")
    difficulty: str = Field("Beginner", description="Beginner, Intermediate, or Advanced")
    estimated_minutes: int = Field(60, description="Estimated study duration in minutes")


class AIRoadmapResponse(BaseModel):
    """Schema for complete structured learning roadmap generated by AI."""
    title: str = Field(..., description="Title of the learning roadmap")
    description: str = Field(..., description="High level roadmap summary")
    topics: List[AIRoadmapTopic] = Field(..., min_length=1, description="List of ordered topics")


class AITopicContentResponse(BaseModel):
    """Schema for structured educational topic material generated by AI."""
    summary: str = Field(..., description="2-3 sentence overview of the topic")
    explanation: str = Field(..., description="Detailed, structured explanation with a real-world analogy")
    code_examples: str = Field(..., description="Working, well-commented code snippets")
    common_mistakes: str = Field(..., description="Common pitfalls, anti-patterns, and debugging tips")
    key_takeaways: str = Field(..., description="Summary bullet points for quick retention")


class AIAssessmentQuestion(BaseModel):
    """Schema for individual assessment question."""
    question_text: str = Field(..., description="Multiple choice question prompt")
    options: List[str] = Field(..., min_length=2, max_length=5, description="List of answer choices")
    correct_option_index: int = Field(..., ge=0, description="0-indexed integer of the correct option")
    explanation: str = Field(..., description="Brief explanation why the answer is correct")
    concept_tag: str = Field(..., description="Specific concept or sub-topic tested, e.g. 'Polymorphism'")


class AIAssessmentResponse(BaseModel):
    """Schema for complete topic assessment quiz generated by AI."""
    title: str = Field(..., description="Assessment quiz title")
    passing_score_percentage: int = Field(70, ge=50, le=100, description="Passing score threshold percentage")
    questions: List[AIAssessmentQuestion] = Field(..., min_length=2, description="List of assessment questions")


class AITutorResponse(BaseModel):
    """Schema for structured AI Tutor response to a student question."""
    explanation: str = Field(..., description="Educational explanation tailored to student skill level")
    code_example: Optional[str] = Field(None, description="Illustrative code example if relevant")
    common_mistake: Optional[str] = Field(None, description="Common pitfall related to the question")
    practice_question: Optional[str] = Field(None, description="Quick practice or self-check question")
    is_topic_related: bool = Field(True, description="Whether the question is related to the current topic")


class AIService:

    """
    AI Service Adapter providing structured generation and token management.
    Can be swapped or extended for different models (e.g. Gemma, local LLMs).
    """

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.GEMINI_API_KEY
        self.model_name = "gemini-3.1-flash-lite"
        self._client = None

        if self.api_key and self.api_key.strip():
            try:
                from google import genai
                self._client = genai.Client(api_key=self.api_key)
            except Exception as e:
                logger.warning(f"Could not initialize Google GenAI Client: {e}")
                self._client = None

    def is_available(self) -> bool:
        """Returns True if the Gemini client is initialized with an API key."""
        if self._client is None:
            key = settings.GEMINI_API_KEY or self.api_key
            if key and key.strip():
                try:
                    from google import genai
                    self.api_key = key.strip()
                    self._client = genai.Client(api_key=self.api_key)
                except Exception as e:
                    logger.warning(f"Could not initialize Google GenAI Client: {e}")
        return self._client is not None

    def generate_learning_roadmap(
        self,
        goal_title: str,
        profile_context: Optional[Dict[str, Any]] = None,
        learning_level: str = "beginner",
    ) -> AIRoadmapResponse:
        """
        Generates an individualized 25-30 topic learning roadmap for a student.
        """
        if not self.is_available():
            logger.info(f"Gemini API key not configured. Using domain template fallback for {learning_level} roadmap.")
            return self._fallback_roadmap(goal_title, learning_level)

        context_parts = [f"Target Goal: {goal_title}", f"Learning Level: {learning_level.upper()}"]
        if profile_context:
            if "education_level" in profile_context:
                context_parts.append(f"Education: {profile_context['education_level']}")
            if "weekly_hours_available" in profile_context:
                context_parts.append(f"Weekly Time: {profile_context['weekly_hours_available']} hrs/week")
            if "preferred_learning_style" in profile_context:
                context_parts.append(f"Style: {profile_context['preferred_learning_style']}")

        learner_context_str = "; ".join(context_parts)

        system_instruction = (
            f"You are an expert curriculum designer. Generate a comprehensive, prerequisite-ordered "
            f"learning roadmap containing between 25 and 30 distinct, logically progressing topics "
            f"for a {learning_level.upper()} level student aiming for '{goal_title}'.\n"
            f"Each topic must represent an incremental milestone with clear dependencies.\n"
            f"Respond strictly in valid JSON matching this schema:\n"
            f'{{"title": string, "description": string, "topics": [{{"title": string, "description": string, "sequence_order": int, "difficulty": string, "estimated_minutes": int}}]}}'
        )

        user_prompt = f"Create a comprehensive 25-30 topic personalized learning roadmap for profile: {learner_context_str}."

        try:
            from google.genai import types

            response = self._client.models.generate_content(
                model=self.model_name,
                contents=user_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    response_mime_type="application/json",
                    temperature=0.2,
                ),
            )

            raw_text = response.text.strip()
            parsed_data = json.loads(raw_text)
            validated_roadmap = AIRoadmapResponse.model_validate(parsed_data)
            if len(validated_roadmap.topics) >= 1:
                return validated_roadmap
            # If AI returned no topics, fallback to comprehensive 25-topic template
            logger.warning(f"Gemini returned empty topics. Merging with curated fallback.")
            return self._fallback_roadmap(goal_title, learning_level)

        except Exception as e:
            logger.error(f"Gemini API call or JSON validation failed: {e}. Activating fallback.")
            return self._fallback_roadmap(goal_title, learning_level)

    def generate_topic_content(
        self,
        topic_title: str,
        goal_title: str,
        profile_context: Optional[Dict[str, Any]] = None,
    ) -> AITopicContentResponse:
        """
        Generates deep, topic-specific educational content:
        Summary, explanation with real-world analogy, annotated code snippet, common mistakes, and takeaways.
        """
        if not self.is_available():
            logger.info(f"Gemini API key not configured. Using domain template fallback for topic '{topic_title}'.")
            return self._fallback_topic_content(topic_title, goal_title)

        skill_level = profile_context.get("current_skill_level", "Beginner") if profile_context else "Beginner"
        learning_style = profile_context.get("preferred_learning_style", "Practical") if profile_context else "Practical"

        system_instruction = (
            "You are a friendly, senior software engineer and computer science tutor. "
            "Explain the technical topic clearly and thoroughly for the specified learner level. "
            "Always include a real-world analogy, clean code snippets with explanations, "
            "common beginner pitfalls/bugs, and bulleted takeaways. "
            "Respond strictly in valid JSON with keys: 'summary', 'explanation', 'code_examples', 'common_mistakes', 'key_takeaways'."
        )

        user_prompt = (
            f"Topic: {topic_title}\n"
            f"Overarching Goal: {goal_title}\n"
            f"Learner Skill Level: {skill_level}\n"
            f"Learner Preferred Style: {learning_style}\n"
            "Provide structured educational content for this topic."
        )

        try:
            from google.genai import types

            response = self._client.models.generate_content(
                model=self.model_name,
                contents=user_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    response_mime_type="application/json",
                    temperature=0.3,
                ),
            )

            raw_text = response.text.strip()
            parsed_data = json.loads(raw_text)
            validated_content = AITopicContentResponse.model_validate(parsed_data)
            return validated_content

        except Exception as e:
            logger.error(f"Gemini topic content generation failed: {e}. Activating fallback.")
            return self._fallback_topic_content(topic_title, goal_title)

    def _fallback_roadmap(self, goal_title: str, learning_level: str = "beginner") -> AIRoadmapResponse:
        """Deterministic 25-topic fallback for roadmap generation."""
        from app.services.learning_service import _get_default_topics_for_goal

        topics_data = _get_default_topics_for_goal(goal_title, learning_level)
        roadmap_topics: List[AIRoadmapTopic] = []

        for idx, item in enumerate(topics_data, start=1):
            roadmap_topics.append(
                AIRoadmapTopic(
                    title=item["title"],
                    description=item["description"],
                    sequence_order=idx,
                    difficulty=item.get("difficulty", learning_level.capitalize()),
                    estimated_minutes=item.get("minutes", 50),
                )
            )

        return AIRoadmapResponse(
            title=f"{goal_title} {learning_level.capitalize()} Learning Journey",
            description=f"Curated 25-topic step-by-step learning roadmap for mastering {goal_title} at the {learning_level.capitalize()} level.",
            topics=roadmap_topics,
        )

    def _fallback_topic_content(self, topic_title: str, goal_title: str) -> AITopicContentResponse:
        """Deterministic fallback for topic educational content."""
        return AITopicContentResponse(
            summary=f"Core concepts, syntax, and principles of {topic_title} in the context of {goal_title}.",
            explanation=(
                f"### Understanding {topic_title}\n\n"
                f"{topic_title} is an essential foundation for {goal_title}. "
                "Think of it like building the foundation of a house: before you can add complex features, "
                "you must understand how the fundamental building blocks interconnect and execute.\n\n"
                "Key concepts include understanding memory layout, execution flow, scope, and encapsulation."
            ),
            code_examples=(
                f"# Example: Core demonstration of {topic_title}\n\n"
                "def demonstrate_concept():\n"
                "    \"\"\"Illustrates standard usage pattern.\"\"\"\n"
                f"    data = ['item1', 'item2', 'item3']\n"
                "    result = [item.upper() for item in data]\n"
                "    return result\n\n"
                "if __name__ == '__main__':\n"
                "    print(demonstrate_concept())\n"
            ),
            common_mistakes=(
                f"1. **Scope Confusion:** Modifying variables outside the local namespace without proper scoping.\n"
                f"2. **Type Incompatibility:** Assuming automatic conversion without explicit parsing.\n"
                f"3. **Missing Error Handling:** Failing to guard against null/empty values or missing keys."
            ),
            key_takeaways=(
                f"• {topic_title} forms a foundational pillar for {goal_title}.\n"
                f"• Always write modular, readable code and verify edge cases.\n"
                f"• Practice with small exercises before moving to complex projects."
            ),
        )

    def generate_topic_assessment(
        self,
        topic_title: str,
        goal_title: str,
        profile_context: Optional[Dict[str, Any]] = None,
    ) -> AIAssessmentResponse:
        """
        Generates a 15-question multiple-choice assessment quiz bank for a topic.
        Considers student skill level to ensure appropriate difficulty and diverse question types.
        """
        if not self.is_available():
            logger.info(f"Gemini API key not configured. Using deterministic fallback 15-question assessment for '{topic_title}'.")
            return self._fallback_topic_assessment(topic_title, goal_title)

        skill_level = profile_context.get("current_skill_level", "Beginner") if profile_context else "Beginner"

        system_instruction = (
            "You are an expert computer science professor creating an objective 15-question mastery assessment quiz. "
            "Generate exactly 15 distinct, high-quality multiple-choice questions testing:\n"
            "- Conceptual foundations (4 questions)\n"
            "- Code output & syntax analysis (4 questions)\n"
            "- Common bug detection & debugging (4 questions)\n"
            "- Real-world scenario application (3 questions)\n"
            "Each question must have 4 distinct options, a 0-indexed correct_option_index, an educational explanation, "
            "and a concept_tag. Respond strictly in valid JSON matching schema:\n"
            '{"title": string, "passing_score_percentage": int, "questions": [{"question_text": string, "options": [string], "correct_option_index": int, "explanation": string, "concept_tag": string}]}'
        )

        user_prompt = (
            f"Topic: {topic_title}\n"
            f"Learning Goal: {goal_title}\n"
            f"Target Student Skill Level: {skill_level}\n"
            "Generate a 15-question mastery assessment quiz."
        )

        try:
            from google.genai import types

            response = self._client.models.generate_content(
                model=self.model_name,
                contents=user_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    response_mime_type="application/json",
                    temperature=0.2,
                ),
            )

            raw_text = response.text.strip()
            parsed_data = json.loads(raw_text)
            validated_assessment = AIAssessmentResponse.model_validate(parsed_data)
            if len(validated_assessment.questions) >= 1:
                return validated_assessment
            return self._fallback_topic_assessment(topic_title, goal_title, skill_level)

        except Exception as e:
            logger.error(f"Gemini assessment generation failed: {e}. Activating fallback.")
            return self._fallback_topic_assessment(topic_title, goal_title, skill_level)

    def _fallback_topic_assessment(self, topic_title: str, goal_title: str, skill_level: str = "Beginner") -> AIAssessmentResponse:
        """Deterministic fallback 15-question assessment quiz."""
        questions = [
            AIAssessmentQuestion(
                question_text=f"1. What is the fundamental purpose and core utility of {topic_title} in {goal_title}?",
                options=[
                    f"To structure, encapsulate, and execute logic related to {topic_title}",
                    "To format raw string representations in standard console output",
                    "To bypass type checking and disable compiler safety constraints",
                    "To manually allocate hardware registers in physical memory",
                ],
                correct_option_index=0,
                explanation=f"{topic_title} establishes the structured foundations and execution logic necessary for {goal_title}.",
                concept_tag=f"{topic_title} Fundamentals",
            ),
            AIAssessmentQuestion(
                question_text=f"2. Which of the following best describes the primary design benefit of applying {topic_title}?",
                options=[
                    "It eliminates the need for unit testing and automated validation",
                    "It improves modularity, maintainability, and code reusability",
                    "It converts interpreted code directly into machine assembly without parsing",
                    "It forces all variables to share a single global namespace",
                ],
                correct_option_index=1,
                explanation="Modularity and reusability are foundational software engineering advantages of proper component design.",
                concept_tag=f"{topic_title} Design Principles",
            ),
            AIAssessmentQuestion(
                question_text=f"3. When initializing and configuring components in {topic_title}, what is considered a critical best practice?",
                options=[
                    "Hardcoding database connection secrets directly in source files",
                    "Avoiding explicit type annotations and ignoring error states",
                    "Encapsulating internal state and validating parameters at boundaries",
                    "Using global mutable state across concurrent execution threads",
                ],
                correct_option_index=2,
                explanation="Boundary parameter validation and state encapsulation prevent corrupted states and unexpected runtime failures.",
                concept_tag=f"{topic_title} Best Practices",
            ),
            AIAssessmentQuestion(
                question_text=f"4. What type of defect or error is most commonly encountered when ignoring scoping rules in {topic_title}?",
                options=[
                    "Unintended variable shadowing and race conditions across scopes",
                    "Hardware CPU cache line invalidation",
                    "Automatic deletion of source code files from disk",
                    "Instant operating system kernel panic",
                ],
                correct_option_index=0,
                explanation="Improper scope boundaries lead to variable shadowing, state pollution, and unpredictable side effects.",
                concept_tag=f"{topic_title} Common Pitfalls",
            ),
            AIAssessmentQuestion(
                question_text=f"5. In the context of {topic_title}, how should unexpected runtime exceptions and error conditions be handled?",
                options=[
                    "By catching base exceptions and silently continuing with empty blocks",
                    "By using structured try-catch blocks and logging meaningful contextual messages",
                    "By terminating the entire operating system process immediately",
                    "By retrying the exact failing operation in an infinite while loop",
                ],
                correct_option_index=1,
                explanation="Structured exception handling and actionable contextual logging ensure system resilience and debuggability.",
                concept_tag=f"{topic_title} Error Handling",
            ),
            AIAssessmentQuestion(
                question_text=f"6. Which time complexity characteristic is generally expected for indexed access in standard {topic_title} collections?",
                options=[
                    "O(N!) factorial time complexity",
                    "O(N^2) quadratic time complexity",
                    "O(1) constant time complexity for direct array indexing",
                    "O(2^N) exponential time complexity",
                ],
                correct_option_index=2,
                explanation="Direct array and contiguous memory indexing provides O(1) constant time access.",
                concept_tag=f"{topic_title} Performance Analysis",
            ),
            AIAssessmentQuestion(
                question_text=f"7. Consider a scenario where multiple execution units access shared state in {topic_title}. What mechanism is required?",
                options=[
                    "Ignoring concurrency since modern operating systems prevent all race conditions",
                    "Applying mutual exclusion, synchronization locks, or atomic primitives",
                    "Converting all data structures to global string variables",
                    "Increasing the system clock speed",
                ],
                correct_option_index=1,
                explanation="Synchronization primitives and thread-safe data structures prevent data corruption under concurrent access.",
                concept_tag=f"{topic_title} Concurrency & Thread Safety",
            ),
            AIAssessmentQuestion(
                question_text=f"8. What is the consequence of failing to release resources (e.g. database connections, file streams) in {topic_title}?",
                options=[
                    "Resource exhaustion and memory leaks over prolonged execution",
                    "Automatic compilation of faster machine code",
                    "Immediate reduction in disk storage usage",
                    "Zero effect because garbage collectors close all external sockets instantly",
                ],
                correct_option_index=0,
                explanation="Unclosed I/O streams and connections hold operating system handles, eventually causing connection pool exhaustion.",
                concept_tag=f"{topic_title} Resource Management",
            ),
            AIAssessmentQuestion(
                question_text=f"9. Which of the following statements regarding immutability in {topic_title} is accurate?",
                options=[
                    "Immutable objects cannot be modified after construction, making them inherently thread-safe",
                    "Immutable objects occupy zero bytes of heap memory",
                    "Immutability is only allowed for integer primitive types",
                    "Immutable objects cause fatal runtime crashes when read by multiple functions",
                ],
                correct_option_index=0,
                explanation="Immutable objects guarantee safe concurrent reads without requiring synchronization locks.",
                concept_tag=f"{topic_title} Immutability Patterns",
            ),
            AIAssessmentQuestion(
                question_text=f"10. When writing unit tests for a module implemented in {topic_title}, what should be the primary objective?",
                options=[
                    "Testing only the simplest happy path with hardcoded mock return values",
                    "Verifying edge cases, invalid inputs, boundary values, and expected error branches",
                    "Making sure unit test code executes without any assertion statements",
                    "Writing tests that only pass on developer machines",
                ],
                correct_option_index=1,
                explanation="Comprehensive testing requires validating boundary conditions, edge cases, and failure modes with assertions.",
                concept_tag=f"{topic_title} Automated Testing",
            ),
            AIAssessmentQuestion(
                question_text=f"11. In an object-oriented architecture for {topic_title}, what does the principle of Polymorphism enable?",
                options=[
                    "Treating objects of different sub-types through a unified common interface",
                    "Enforcing that all classes have exactly one private method",
                    "Restricting inheritance to a maximum of one level",
                    "Disabling dynamic dispatch at runtime",
                ],
                correct_option_index=0,
                explanation="Polymorphism allows decoupled code to operate on polymorphic interfaces rather than rigid concrete implementations.",
                concept_tag=f"{topic_title} Polymorphism & OOP",
            ),
            AIAssessmentQuestion(
                question_text=f"12. What debugging approach is most effective when isolating a logic error in {topic_title}?",
                options=[
                    "Randomly changing operators until test output changes",
                    "Setting breakpoints, inspecting variable state frames, and tracing execution paths",
                    "Deleting all error handling try-catch blocks",
                    "Reinstalling the operating system",
                ],
                correct_option_index=1,
                explanation="Systematic breakpoint debugging and stack frame inspection allow deterministic localization of state errors.",
                concept_tag=f"{topic_title} Debugging & Diagnostics",
            ),
            AIAssessmentQuestion(
                question_text=f"13. When designing interfaces or function signatures in {topic_title}, why is high cohesion desirable?",
                options=[
                    "It ensures a component focuses on a single well-defined responsibility",
                    "It combines unrelated concerns into one massive monolithic file",
                    "It prevents the program from using helper methods",
                    "It slows down execution for security purposes",
                ],
                correct_option_index=0,
                explanation="High cohesion ensures that each module has a clear, singular responsibility, simplifying maintenance.",
                concept_tag=f"{topic_title} Architectural Cohesion",
            ),
            AIAssessmentQuestion(
                question_text=f"14. What is a key security risk when constructing queries or dynamic commands in {topic_title} with user input?",
                options=[
                    "SQL Injection or Command Injection due to unvalidated concatenation",
                    "Automatic compilation of source code into binary",
                    "Automatic enforcement of strong passwords",
                    "Reduction in network latency",
                ],
                correct_option_index=0,
                explanation="String concatenation with unvalidated user input opens severe injection vulnerabilities; parameterization is required.",
                concept_tag=f"{topic_title} Application Security",
            ),
            AIAssessmentQuestion(
                question_text=f"15. As a {goal_title} practitioner mastering {topic_title}, what is the recommended next step after completing this topic?",
                options=[
                    "Apply the concepts in hands-on code exercises and advance to the next sequential prerequisite",
                    "Stop studying and ignore subsequent prerequisite roadmap modules",
                    "Rewrite all previous code in a different incompatible framework",
                    "Delete project repositories",
                ],
                correct_option_index=0,
                explanation="Reinforcing learning through practical application before advancing guarantees mastery of prerequisites.",
                concept_tag=f"{topic_title} Roadmap Progression",
            ),
        ]

        return AIAssessmentResponse(
            title=f"{topic_title} Mastery Assessment",
            passing_score_percentage=70,
            questions=questions,
        )

    def ask_topic_tutor(
        self,
        topic_title: str,
        goal_title: str,
        student_level: str,
        question: str,
        topic_description: str = "",
        topic_difficulty: str = "Beginner",
        topic_content: Optional[Dict[str, str]] = None,
        conversation_history: Optional[List[Any]] = None,
        topic_summary: Optional[str] = None,
    ) -> AITutorResponse:
        """
        Interactive Gemini AI Topic Tutor answering a student question scoped to the current topic.
        Grounded in the current topic context, description, difficulty, student level, goal,
        and actual lesson content, while maintaining multi-turn context from conversation history.
        """
        if not self.is_available():
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Gemini API key is not configured. Please add GEMINI_API_KEY to your backend .env file to enable the AI Tutor.",
            )

        # Precise tutor system instruction
        system_instruction = (
            "You are an AI learning tutor inside a personalized learning platform.\n\n"
            "Your job is to help the student understand the current lesson.\n\n"
            "Current topic and supplied lesson content are the primary context.\n\n"
            "Answer clearly, accurately and at the student's learning level.\n\n"
            "Use the conversation history to understand follow-up questions.\n\n"
            "If the student asks for clarification, explain the same concept in a different and simpler way.\n\n"
            "Do not pretend to know information that is unsupported or uncertain.\n\n"
            "Do not invent facts.\n\n"
            "Stay relevant to the current learning topic.\n\n"
            "If a question is unrelated to the current topic, politely redirect the student to the current lesson.\n\n"
            "Your goal is understanding, not just producing an answer.\n\n"
            "TUTOR BEHAVIOR GUIDELINES:\n"
            "1. Grounding: The supplied lesson content is your primary educational context. Do not answer as a generic chatbot.\n"
            "2. Follow-Up Understanding: If the student asks 'why?', 'explain that again', 'give another example', 'what is the difference?', or 'I didn't understand', use the conversation history to resolve what 'that' refers to and maintain continuous conversational context.\n"
            "3. Flexible Response Formatting: Naturally choose the most appropriate structure for the question:\n"
            "   - Simple question: short, direct explanation + intuitive example.\n"
            "   - Conceptual question: clear explanation + example + key takeaways.\n"
            "   - Programming/technical question: explanation + annotated working code snippet + brief explanation of the code.\n"
            "   - 'I don't understand': re-explain using simpler language, fresh analogy, and a different example.\n"
            "   - Avoid unnecessarily long or repetitive boilerplate.\n"
            "4. Unrelated Queries: If the question is outside the scope of the current topic (e.g. food recipes, sports, celebrity gossip), set is_topic_related=false, and provide a polite redirect asking them to focus on the current lesson.\n"
            "5. Output Schema: Respond strictly with valid JSON matching:\n"
            '{"explanation": string, "is_topic_related": bool, "code_example": string or null, "common_mistake": string or null, "practice_question": string or null}'
        )

        prompt_parts = [
            "=== CURRENT LEARNING CONTEXT ===",
            f"Topic Title: {topic_title}",
            f"Topic Description: {topic_description or 'N/A'}",
            f"Topic Difficulty: {topic_difficulty}",
            f"Student Learning Level: {student_level}",
            f"Student Career Goal: {goal_title}",
        ]

        # Inject actual lesson content for primary educational grounding
        if topic_content:
            prompt_parts.append("\n=== SUPPLIED LESSON CONTENT (PRIMARY EDUCATIONAL GROUNDING) ===")
            if topic_content.get("summary"):
                prompt_parts.append(f"[Overview]\n{topic_content['summary']}")
            if topic_content.get("explanation"):
                prompt_parts.append(f"[Concept Explanation]\n{topic_content['explanation']}")
            if topic_content.get("code_examples"):
                prompt_parts.append(f"[Code Examples]\n{topic_content['code_examples']}")
            if topic_content.get("common_mistakes"):
                prompt_parts.append(f"[Common Mistakes]\n{topic_content['common_mistakes']}")
            if topic_content.get("key_takeaways"):
                prompt_parts.append(f"[Key Takeaways]\n{topic_content['key_takeaways']}")
        elif topic_summary:
            prompt_parts.append(f"\n=== SUPPLIED LESSON SUMMARY ===\n{topic_summary}")

        # Inject controlled recent conversation history (last 8 messages / 4 turns)
        if conversation_history:
            recent_history = conversation_history[-8:]
            prompt_parts.append("\n=== RECENT CONVERSATION HISTORY ===")
            for msg in recent_history:
                role = msg.get("role") if isinstance(msg, dict) else getattr(msg, "role", "user")
                role_label = "Student" if role == "user" else "Tutor"
                content_text = msg.get("content") if isinstance(msg, dict) else getattr(msg, "content", "")
                if content_text:
                    prompt_parts.append(f"{role_label}: {content_text.strip()[:600]}")

        prompt_parts.append("\n=== CURRENT STUDENT QUESTION ===")
        prompt_parts.append(f"Student: {question.strip()}")

        from google.genai import types

        # Candidate models to try in case of model retirement (404) or transient high-demand spikes (503)
        candidate_models = [self.model_name]
        for fallback_m in ["gemini-3.1-flash-lite", "gemini-3.5-flash-lite", "gemini-3.8-flash"]:
            if fallback_m not in candidate_models:
                candidate_models.append(fallback_m)

        last_exception = None
        for current_model in candidate_models:
            try:
                logger.info(f"Calling Gemini Topic Tutor using model '{current_model}'...")
                response = self._client.models.generate_content(
                    model=current_model,
                    contents="\n".join(prompt_parts),
                    config=types.GenerateContentConfig(
                        system_instruction=system_instruction,
                        response_mime_type="application/json",
                        temperature=0.3,
                    ),
                )

                if not response or not hasattr(response, "text") or not response.text or not response.text.strip():
                    raise HTTPException(
                        status_code=status.HTTP_502_BAD_GATEWAY,
                        detail="AI Tutor returned an empty response from Gemini. Please click Retry.",
                    )

                raw_text = response.text.strip()
                if raw_text.startswith("```"):
                    parts = raw_text.split("```", 2)
                    if len(parts) >= 2:
                        raw_text = parts[1]
                    if raw_text.startswith("json"):
                        raw_text = raw_text[4:].strip()
                    if raw_text.endswith("```"):
                        raw_text = raw_text[:-3].strip()

                try:
                    parsed_data = json.loads(raw_text)
                except json.JSONDecodeError as json_err:
                    logger.error(f"Failed to parse Gemini tutor JSON: {json_err}. Raw text: {raw_text[:200]}")
                    raise HTTPException(
                        status_code=status.HTTP_502_BAD_GATEWAY,
                        detail="AI Tutor received an invalid response format from Gemini. Please click Retry.",
                    )

                # Update default model to the one that succeeded
                self.model_name = current_model
                return AITutorResponse.model_validate(parsed_data)

            except HTTPException:
                raise
            except Exception as e:
                last_exception = e
                err_str = str(e)
                logger.warning(f"Model '{current_model}' failed with {type(e).__name__}: {err_str[:200]}. Trying next candidate if available...")
                # If it's a 404 or 503 on this specific model, proceed to the next candidate
                if "404" in err_str or "not_found" in err_str.lower() or "503" in err_str or "unavailable" in err_str.lower():
                    continue
                # For auth/rate-limit errors, do not loop through other models
                break

        # If all candidate models failed, construct transparent sanitized error
        e = last_exception or Exception("All candidate Gemini models failed")
        err_msg = str(e)
        # Strictly sanitize API key from any error message
        api_key_val = self.api_key or settings.GEMINI_API_KEY
        if api_key_val and len(api_key_val) > 4:
            err_msg = err_msg.replace(api_key_val, "[REDACTED_API_KEY]")

        logger.error(f"All Gemini topic tutor model attempts failed. Last error [{type(e).__name__}]: {err_msg}")

        err_lower = err_msg.lower()
        if "timeout" in err_lower or "timed out" in err_lower:
            raise HTTPException(
                status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                detail=f"AI Tutor request timed out connecting to Gemini: {err_msg[:250]}. Please click Retry.",
            )
        if "429" in err_lower or "quota" in err_lower or "resource_exhausted" in err_lower:
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail=f"Gemini API rate limit reached: {err_msg[:250]}. Please wait a moment and click Retry.",
            )
        if "404" in err_lower:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini model not found: {err_msg[:250]}. Please click Retry.",
            )
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Gemini AI Tutor error ({type(e).__name__}): {err_msg[:300]}. Please click Retry.",
        )


# Singleton instance of AIService
ai_service = AIService()


